Sat, 26 Dec 2020 14:51:03  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/loginReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D4635940>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:03  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46DD7F0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:03  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46DD7F0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E62E8>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E62E8>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E62E8>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E6BE0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E6BE0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E6BE0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:04  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000247D46E6BE0>: Failed to establish a new connection: [WinError 10065] 套接字操作尝试一个无法连接的主机。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/loginReq (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F330A5B70>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F331738D0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F331738D0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F331853C8>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F331853C8>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F331853C8>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F33185CC0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F33185CC0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F33185CC0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
Sat, 26 Dec 2020 14:51:07  myLogger.py  error [line:42] ERROR 请求报错了:HTTPConnectionPool(host='120.55.190.222', port=7080): Max retries exceeded with url: /api/mgr/sq_mgr/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021F33185CC0>: Failed to establish a new connection: [WinError 10051] 向一个无法连接的网络尝试了一个套接字操作。'))
